import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(
    page_title="Tier 4: Single-Cell Transcriptomics | GenomeTech Studio",
    page_icon="🧬",
    layout="wide"
)

st.markdown("""
<style>
    .stApp {
        background: radial-gradient(circle at top right, #1e1b4b 0%, #0f172a 60%, #020617 100%);
        color: #f1f5f9 !important;
        font-family: 'Inter', sans-serif;
    }
    .tier-header {
        background: linear-gradient(90deg, #3b82f6 0%, #1d4ed8 100%);
        padding: 2rem;
        border-radius: 16px;
        margin-bottom: 2rem;
        border: 1px solid rgba(96, 165, 250, 0.4);
    }
    .module-card {
        background: rgba(30, 41, 59, 0.7);
        border: 1px solid rgba(59, 130, 246, 0.3);
        border-radius: 12px;
        padding: 1.2rem;
        margin-bottom: 1rem;
    }
</style>
""", unsafe_allow_html=True)

# Navigation header back to main app
if st.button("← Back to OmicsExpress Launchpad"):
    st.query_params.clear()
    st.switch_page("app.py")

st.markdown("""
<div class="tier-header">
    <span style="background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 999px; font-size: 0.8rem; font-weight: bold;">TIER 4 ADVANCED PIPELINE</span>
    <h1 style="color: white; margin-top: 10px;">Single-Cell Transcriptomics Profiling</h1>
    <p style="color: #93c5fd; margin: 0;">Full-stack scRNA-seq analysis from raw count matrices to annotated UMAP projections and marker gene heatmaps.</p>
</div>
""", unsafe_allow_html=True)

col1, col2 = st.columns([1, 2], gap="large")

with col1:
    st.markdown("### 🎛️ Configure Your Analysis")
    
    use_bundle = st.checkbox("🔥 Full Tier 4 Bundle (Save $100)", value=True)
    
    if not use_bundle:
        inc_matrix = st.checkbox("Matrix Processing ($150)", value=True)
        inc_seurat = st.checkbox("Seurat Clustering ($120)", value=True)
        inc_celltype = st.checkbox("Cell Type ID Maps ($100)", value=True)
        inc_umap = st.checkbox("UMAP Projections ($80)", value=True)
        
        total_price = (150 if inc_matrix else 0) + \
                      (120 if inc_seurat else 0) + \
                      (100 if inc_celltype else 0) + \
                      (80 if inc_umap else 0)
    else:
        total_price = 450
        st.info("Bundle active: All 4 modules included for $450.")

    st.markdown(f"### Total Investment: <span style='color: #38bdf8;'>${total_price} USD</span>", unsafe_allow_html=True)
    
    st.markdown("---")
    st.markdown("**Ready to run your dataset?**")
    client_email = st.text_input("Your Research Email:", placeholder="pi@university.edu")
    
    if st.button("Proceed to Project Intake & 30% Advance ($" + str(round(total_price * 0.3, 2)) + ")"):
        if client_email:
            st.success(f"Intake reservation generated for {client_email}! Redirecting to project coordination...")
            st.markdown(f"[Click here to submit dataset & requirements via Google Form](https://forms.gle/9gqcYrc3NjtAn7z59)")
        else:
            st.warning("Please enter your research email address.")

with col2:
    st.markdown("### 📊 Interactive Preview & QC Inspector")
    st.markdown("Inspect mock single-cell clustering outputs generated by our automated Seurat pipeline:")
    
    # Mock single cell cluster data table
    mock_clusters = pd.DataFrame({
        "Cluster ID": [0, 1, 2, 3, 4, 5],
        "Cell Type Annotation": ["CD4+ T Cells", "CD8+ Cytotoxic T", "CD14+ Monocytes", "B Cells", "NK Cells", "Dendritic Cells"],
        "Marker Genes": ["IL7R, CD3D", "CD8A, GZMB", "LYZ, S100A9", "MS4A1, CD79A", "NKG7, GNLY", "FCER1A, CST3"],
        "Cell Count": [4120, 2890, 2450, 1120, 890, 310],
        "Mean Expression (AvgLog2FC)": [2.41, 2.18, 1.95, 2.67, 2.12, 1.84]
    })
    
    st.dataframe(mock_clusters, use_container_width=True)
    
    st.markdown("#### 🔬 Sample Visualization Output")
    st.markdown("*(Below is a preview of the high-resolution vector SVG UMAP clusters delivered with your run)*")
    
    # Generate mock scatter plot data for UMAP preview
    chart_data = pd.DataFrame(
        np.random.randn(200, 2),
        columns=['UMAP_1', 'UMAP_2']
    )
    chart_data['Cluster'] = np.random.choice(['CD4+ T', 'CD8+ T', 'Monocytes', 'B Cells'], size=200)
    
    st.scatter_chart(chart_data, x='UMAP_1', y='UMAP_2', color='Cluster')